# Generated by Django 3.1.1 on 2020-09-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(max_length=255, upload_to='static/img/place/')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('categoria', models.IntegerField(default=0)),
                ('cover', models.ImageField(max_length=255, upload_to='static/img/place/')),
                ('price', models.IntegerField(default=0)),
                ('fotos', models.ManyToManyField(to='Aconchego.Fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_cama', models.IntegerField(default=0)),
                ('tipo', models.CharField(max_length=255)),
                ('descricao', models.TextField(null=True)),
                ('cover', models.ImageField(max_length=255, null=True, upload_to='static/img/place/')),
                ('price', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkindate', models.DateField(null=True)),
                ('checkoutdate', models.DateField(null=True)),
                ('adultos', models.IntegerField(default=0)),
                ('crianca', models.IntegerField(default=0)),
                ('preco', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aconchego.customer')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aconchego.hotel')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aconchego.room')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='rooms',
            field=models.ManyToManyField(to='Aconchego.Room'),
        ),
    ]
