# Generated by Django 3.1.1 on 2020-09-22 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('categoria', models.IntegerField(default=0)),
                ('cover', models.ImageField(max_length=255, upload_to='static/img/place/')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Numero_cama', models.IntegerField(default=0)),
                ('tipo', models.CharField(max_length=255)),
                ('descricao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkindate', models.DateField(null=True)),
                ('checkoutdate', models.DateField(null=True)),
                ('adultos', models.IntegerField(default=0)),
                ('crianca', models.IntegerField(default=0)),
                ('preco', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aconchego.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel_Fotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aconchego.hotel')),
            ],
        ),
    ]
