# Generated by Django 3.1.1 on 2020-09-20 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aconchego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkindate', models.DateField(null=True)),
                ('checkoutdate', models.DateField(null=True)),
                ('adultos', models.IntegerField(default=0)),
                ('crianca', models.IntegerField(default=0)),
                ('preco', models.IntegerField(default=0)),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aconchego.hotel')),
            ],
        ),
    ]
