# Generated by Django 3.1.1 on 2020-09-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aconchego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cover',
            field=models.ImageField(max_length=255, null=True, upload_to='static/img/place/'),
        ),
    ]
