# Generated by Django 3.1.1 on 2020-09-22 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aconchego', '0002_room_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aconchego.hotel')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aconchego.room')),
            ],
        ),
    ]
