# Generated by Django 3.1.1 on 2020-09-20 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aconchego', '0002_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='id_hotel',
            new_name='hotel',
        ),
    ]
