# Generated by Django 3.1.1 on 2020-09-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aconchego', '0003_room_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room_Hotel',
        ),
    ]
