# Generated by Django 3.1.1 on 2020-09-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aconchego', '0003_auto_20200921_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='hotel',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
