# Generated by Django 3.1.1 on 2020-09-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aconchego', '0005_auto_20200921_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
