# Generated by Django 3.1.1 on 2020-09-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aconchego', '0005_hotel_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel_Fotos',
        ),
    ]
