# Generated by Django 3.1.1 on 2020-09-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aconchego', '0006_auto_20200922_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='fotos',
            field=models.ManyToManyField(to='Aconchego.Fotos'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='path',
            field=models.ImageField(max_length=255, upload_to='static/img/place/'),
        ),
    ]
