# Generated by Django 3.1.1 on 2020-09-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aconchego', '0007_auto_20200922_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
