# Generated by Django 3.1.1 on 2020-09-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aconchego', '0009_remove_reserva_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aconchego.hotel'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aconchego.room'),
        ),
    ]
