# Generated by Django 3.1.1 on 2020-09-25 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aconchego', '0011_auto_20200922_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aconchego.customer'),
        ),
    ]
